version: "2"
services:
    web:
        build: .
        #image: php:5-apache
        container_name: moodle-web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./moodle:/var/www/html
            - ./moodledata:/var/www/moodledata
        links:
            - db:db.moodle.dev
        depends_on:
            - db

    db:
        # Moodle 2.7 does not support 5.7.0 which changed storage_engine to default_storage_engine MDL-50633
        image: mysql:5.5
        container_name: moodle-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: moodle
            MYSQL_USER: moodle_dbuser
            MYSQL_PASSWORD: password
        volumes:
            - ./database:/var/lib/mysql